modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="nhamashal"
version="1.0"
displayName="Nhamashal"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="examplemod.png"
credits=""
authors="Coolmenty, Derogona"
description='''

'''